name: Build iOS Framework
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build klibs
        run: ./gradlew iosArm64MainKlibrary iosX64MainKlibrary
      - name: Build XCFrameworks
        run: ./gradlew assembleJsonPath4KXCFramework
      - name: Upload debug XCFramework jsonpath4k
        uses: actions/upload-artifact@v3
        with:
          name: JsonPath4K-debug.xcframework
          path: |
            jsonpath4k/build/XCFrameworks/debug/
      - name: Upload release XCFramework jsonpath4k
        uses: actions/upload-artifact@v3
        with:
          name: JsonPath4K-release.xcframework
          path: |
            jsonpath4k/build/XCFrameworks/release/
